import Link from 'next/link'
import { ArrowUpRight, BookOpen, Check, ChevronRight, Library, Search, ShieldCheck, Sparkles, Users, Workflow } from 'lucide-react'
import { books, publicDescription, publicNav } from '@/lib/biblio-data'
import { AuthForm } from '@/components/auth-form'

const capabilities = [
  { icon: Workflow, title: 'One operating rhythm', text: 'Circulation, cataloging, acquisitions, and reporting in one calm workspace.' },
  { icon: ShieldCheck, title: 'Trusted by design', text: 'Every action is scoped, permissioned, and auditable across your network.' },
  { icon: Users, title: 'Made for people', text: 'Give every librarian the clarity to spend more time with their community.' },
]

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-[#f7f5ef] text-[#17233b]">
    <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
      <Link href="/" className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#142541] text-[#f6e8c2] shadow-xl shadow-[#142541]/15"><Library className="size-5" /></span><span><span className="block text-[15px] font-semibold tracking-tight">BiblioNexus</span><span className="block text-[9px] font-semibold uppercase tracking-[.22em] text-[#71809a]">Library intelligence</span></span></Link>
      <nav className="hidden items-center gap-8 text-sm font-medium text-[#66738a] lg:flex">{publicNav.slice(0, 3).map((item) => <Link key={item.href} href={item.href} className="transition-colors hover:text-[#142541]">{item.label}</Link>)}<Link href="#catalog" className="transition-colors hover:text-[#142541]">Catalog</Link><Link href="#access" className="transition-colors hover:text-[#142541]">Access</Link></nav>
      <div className="flex items-center gap-3"><Link href="/sign-in" className="hidden text-sm font-semibold text-[#52617a] sm:inline">Sign in</Link><Link href="/sign-up" className="rounded-xl bg-[#142541] px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-[#142541]/15 transition-transform hover:-translate-y-0.5">Request access</Link></div>
    </header>
    <section className="relative mx-auto grid max-w-7xl gap-16 px-6 pb-24 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-20">
      <div className="relative z-10"><p className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#d8cda9] bg-[#f6edcf]/70 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.2em] text-[#806d3b]"><Sparkles className="size-3.5" /> The modern library OS</p><h1 className="max-w-3xl text-balance text-5xl font-semibold leading-[.98] tracking-[-.075em] sm:text-7xl lg:text-[6.8rem]">Make every <span className="text-[#a1823b]">shelf</span> feel closer.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#65728a]">{publicDescription} A premium operating system for libraries that want less friction, deeper insight, and more room for the work that matters.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link href="/sign-up" className="group inline-flex items-center gap-3 rounded-xl bg-[#142541] px-5 py-3.5 text-sm font-semibold text-white shadow-xl shadow-[#142541]/20">Build your library workspace <ArrowUpRight className="size-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link><Link href="/opac/search" className="inline-flex items-center gap-2 px-2 py-3.5 text-sm font-semibold text-[#59677e]">Explore the catalog <ChevronRight className="size-4" /></Link></div><div className="mt-12 flex items-center gap-6 border-t border-[#ddd9cc] pt-6 text-xs text-[#78849a]"><span><strong className="block text-xl font-semibold tracking-tight text-[#17233b]">42k+</strong> titles connected</span><span className="h-8 w-px bg-[#ddd9cc]" /><span><strong className="block text-xl font-semibold tracking-tight text-[#17233b]">99.9%</strong> data integrity</span></div></div>
      <div className="relative min-h-[470px] lg:min-h-[570px]"><div className="absolute -right-20 -top-20 size-80 rounded-full bg-[#e5d7aa]/50 blur-3xl" /><div className="absolute bottom-0 left-0 size-64 rounded-full bg-[#b8d0c8]/35 blur-3xl" /><div className="relative mx-auto max-w-[500px] rotate-2 rounded-[2rem] border border-white/70 bg-[#142541] p-3 shadow-2xl shadow-[#142541]/25"><div className="overflow-hidden rounded-[1.4rem] bg-[#f7f5ef]"><div className="flex items-center justify-between border-b border-[#e1ddd2] px-5 py-4"><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-[#142541] text-[#f6e8c2]"><Library className="size-3.5" /></span><span className="text-xs font-semibold">BiblioNexus</span></div><span className="rounded-full bg-[#e5f0e8] px-2 py-1 text-[9px] font-bold text-[#367056]">ALL SYSTEMS LIVE</span></div><div className="grid gap-4 p-5"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#8b96a6]">Good morning, team</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">The library, in focus.</h2></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#142541] p-4 text-white"><p className="text-[10px] text-white/60">Active loans</p><p className="mt-4 text-3xl font-semibold">1,284</p><p className="mt-2 text-[10px] text-[#b9d7c6]">↑ 12.8% this month</p></div><div className="rounded-2xl border border-[#e1ddd2] bg-white p-4"><p className="text-[10px] text-[#8b96a6]">Returns today</p><p className="mt-4 text-3xl font-semibold">86</p><p className="mt-2 text-[10px] text-[#a1823b]">14 awaiting review</p></div></div><div className="rounded-2xl border border-[#e1ddd2] bg-white p-4"><div className="mb-4 flex items-center justify-between"><p className="text-xs font-semibold">Collection health</p><span className="text-[10px] text-[#8b96a6]">Last 30 days</span></div><div className="flex h-24 items-end gap-2">{[35,52,45,68,58,76,64,88,72,94,81,100].map((height, index) => <div key={index} className="flex-1 rounded-t-md bg-[#9eb8b0]" style={{ height: `${height}%`, opacity: index > 8 ? 1 : .55 }} />)}</div></div></div></div></div><div className="absolute -bottom-5 -left-5 rounded-2xl border border-white/80 bg-white/90 p-4 shadow-xl backdrop-blur"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#8b96a6]">Network pulse</p><p className="mt-1 text-sm font-semibold">Everything is connected.</p><div className="mt-3 flex -space-x-2"><span className="grid size-7 place-items-center rounded-full border-2 border-white bg-[#d5b77d] text-[9px] font-bold">AM</span><span className="grid size-7 place-items-center rounded-full border-2 border-white bg-[#9eb8b0] text-[9px] font-bold">JS</span><span className="grid size-7 place-items-center rounded-full border-2 border-white bg-[#d5c9b6] text-[9px] font-bold">+8</span></div></div></div>
    </section>
    <section id="platform" className="border-y border-[#e1ddd2] bg-[#f1eee5] px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#a1823b]">Built for the whole ecosystem</p><h2 className="mt-4 text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Quietly powerful. Obsessively clear.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-3">{capabilities.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-3xl border border-[#ddd9cc] bg-[#f8f6f0] p-6 transition-transform hover:-translate-y-1"><span className="grid size-11 place-items-center rounded-2xl bg-[#e4ece7] text-[#477466]"><Icon className="size-5" /></span><h3 className="mt-7 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#6e7a8e]">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-semibold text-[#a1823b]"><Check className="size-3.5" /> Included in every workspace</span></article>)}</div></div></section>
    <section id="catalog" className="border-y border-[#e1ddd2] bg-[#f1eee5] px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#a1823b]">Explore the collection</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">A catalog made to be discovered.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#6e7a8e]">Search a living collection before you enter the workspace. Every record is designed to feel clear, useful, and close at hand.</p></div><Link href="/opac/search" className="inline-flex items-center gap-2 text-sm font-semibold text-[#142541]">Open full catalog <ArrowUpRight className="size-4" /></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{books.slice(0, 4).map((book) => <Link key={book.id} href={`/opac/book/${book.id}`} className="group rounded-3xl border border-[#ddd9cc] bg-[#f8f6f0] p-5 transition hover:-translate-y-1 hover:border-[#a1823b]"><div className="grid aspect-[4/3] place-items-center rounded-2xl bg-[#e4ece7] text-[#477466]"><BookOpen className="size-10 transition-transform group-hover:scale-105" /></div><p className="mt-5 text-sm font-semibold leading-5 text-[#17233b]">{book.title}</p><p className="mt-1 text-xs text-[#7b8798]">{book.author}</p><span className="mt-5 inline-flex items-center gap-1 text-[11px] font-bold uppercase tracking-[.12em] text-[#a1823b]">View record <ChevronRight className="size-3" /></span></Link>)}</div></div></section>
    <section id="access" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="mb-12 max-w-xl"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#a1823b]">Your workspace awaits</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Sign in or make your library’s next move.</h2><p className="mt-4 text-sm leading-6 text-[#6e7a8e]">Use the secure workspace for staff operations, or create an account to begin your library journey.</p></div><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-[2rem] border border-[#ddd9cc] bg-[#f1eee5] p-6 sm:p-8"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#a1823b]">Returning team</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">Welcome back</h3></div><AuthForm mode="sign-in" /></div><div className="rounded-[2rem] border border-[#142541] bg-[#142541] p-6 text-white sm:p-8"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#f6e8c2]">New workspace</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">Start with BiblioNexus</h3></div><AuthForm mode="sign-up" /></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 text-center lg:px-10"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#a1823b]">Start with a better rhythm</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-semibold tracking-[-.06em] sm:text-6xl">Your next chapter starts here.</h2><Link href="/sign-up" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#142541] px-6 py-3.5 text-sm font-semibold text-white shadow-xl shadow-[#142541]/20">Request access <ArrowUpRight className="size-4" /></Link></section>
    <footer className="border-t border-[#e1ddd2] px-6 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs text-[#8993a3] sm:flex-row sm:items-center sm:justify-between"><span>© 2026 BiblioNexus. Library intelligence, thoughtfully built.</span><span>Secure by design · Human centered · Open to every community</span></div></footer>
  </main>
}
