'use client'

import { useMemo, useState, useTransition } from 'react'
import { Search, ShieldCheck, UserCheck, UserX } from 'lucide-react'
import { updateUserStatus, type AdminRole, type AdminUser } from '@/app/actions/admin-users'
import { cn } from '@/lib/utils'

export function UsersTable({ initialUsers, roles }: { initialUsers: AdminUser[]; roles: AdminRole[] }) {
  const [query, setQuery] = useState('')
  const [users, setUsers] = useState(initialUsers)
  const [pending, startTransition] = useTransition()
  const filtered = useMemo(() => users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase())), [users, query])
  return <section className="flex flex-col gap-5"><div className="flex flex-col gap-3 rounded-2xl border border-border bg-card p-4 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3 rounded-xl border border-border bg-background px-3"><Search className="size-4 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name or email" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none" /></div><div className="flex items-center gap-2 text-sm text-muted-foreground"><ShieldCheck className="size-4" />{roles.length} roles configured</div></div><div className="overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-border bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-4">User</th><th className="px-5 py-4">Roles</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-border">{filtered.map((user) => <tr key={user.id}><td className="px-5 py-4"><p className="font-medium">{user.name}</p><p className="text-xs text-muted-foreground">{user.email}</p></td><td className="px-5 py-4"><div className="flex flex-wrap gap-2">{user.roles.length ? user.roles.map((assignment) => <span key={assignment.id} className="rounded-full bg-primary/10 px-2.5 py-1 text-xs text-primary">{assignment.role.name}{assignment.library?.name ? ` · ${assignment.library.name}` : ''}</span>) : <span className="text-muted-foreground">No roles</span>}</div></td><td className="px-5 py-4"><span className={cn('rounded-full px-2.5 py-1 text-xs font-medium', user.status === 'ACTIVE' ? 'bg-emerald-500/10 text-emerald-700' : 'bg-muted text-muted-foreground')}>{user.status}</span></td><td className="px-5 py-4 text-right"><button disabled={pending} onClick={() => startTransition(async () => { const status = user.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'; await updateUserStatus(user.id, status); setUsers((current) => current.map((item) => item.id === user.id ? { ...item, status } : item)) })} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-medium hover:bg-muted disabled:opacity-50">{user.status === 'ACTIVE' ? <UserX className="size-4" /> : <UserCheck className="size-4" />}{user.status === 'ACTIVE' ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">No users match this search.</p>}</div></section>
}
