'use client'
import { usePathname, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { Bell, BookOpen, ChevronRight, Command, Library, Menu, Moon, Search, Settings2, Sun, Users, X } from 'lucide-react'
import { cn } from '@/lib/utils'
import { signOut, useSession } from '@/lib/auth-client'
import { currentUser, navItems, routeTitle } from '@/lib/biblio-data'

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [mobileOpen, setMobileOpen] = useState(false); const [dark, setDark] = useState(false); const [collapsed, setCollapsed] = useState(false); const [palette, setPalette] = useState(false)
  useEffect(() => { setDark(document.documentElement.classList.contains('dark')); const saved = window.localStorage.getItem('biblionexus-sidebar-collapsed'); setCollapsed(saved === 'true') }, [])
  useEffect(() => { document.documentElement.classList.toggle('dark', dark) }, [dark])
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setPalette(true) } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [])
  const go = (href: string) => { router.push(href); setMobileOpen(false); setPalette(false) }
  const sidebar = <aside className={cn('flex flex-col border-r border-border bg-sidebar transition-all', collapsed ? 'w-20' : 'w-64', mobileOpen ? 'fixed inset-y-0 left-0 z-40 w-72 shadow-2xl lg:static' : 'hidden lg:flex')}><div className="flex h-[72px] items-center gap-3 border-b border-border px-5"><div className="grid size-9 place-items-center rounded-xl bg-sidebar-primary text-sidebar-primary-foreground"><Library className="size-5" /></div>{!collapsed && <div><p className="text-[15px] font-semibold">BiblioNexus</p><p className="text-[10px] uppercase tracking-[.16em] text-muted-foreground">Library intelligence</p></div>}<button className="ml-auto lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X className="size-5" /></button></div><nav className="flex flex-1 flex-col gap-1 overflow-y-auto p-3">{navItems.map((item) => <button key={item.href} onClick={() => go(item.href)} title={collapsed ? item.label : undefined} className={cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground', pathname === item.href || pathname.startsWith(`${item.href}/`) ? 'bg-sidebar-accent font-medium text-sidebar-accent-foreground' : '')}>{item.label === 'Catalog' ? <BookOpen className="size-[17px]" /> : item.label === 'Members' ? <Users className="size-[17px]" /> : item.label === 'Settings' ? <Settings2 className="size-[17px]" /> : <ChevronRight className="size-[17px]" />}{!collapsed && item.label}</button>)}</nav><div className="border-t border-border p-3"><button onClick={() => { const value = !collapsed; setCollapsed(value); window.localStorage.setItem('biblionexus-sidebar-collapsed', String(value)) }} className="w-full rounded-lg px-3 py-2 text-left text-xs text-muted-foreground hover:bg-sidebar-accent">{collapsed ? 'Expand' : 'Collapse menu'}</button></div></aside>
  return <div className="min-h-screen bg-background text-foreground"><div className="flex min-h-screen">{sidebar}<div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-[72px] items-center gap-3 border-b border-border bg-background/90 px-4 backdrop-blur-md sm:px-6"><button className="rounded-lg p-2 hover:bg-muted lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu className="size-5" /></button><div className="hidden items-center gap-2 text-sm text-muted-foreground md:flex"><span>Workspace</span><span>/</span><span className="font-medium text-foreground">{routeTitle(pathname)}</span></div><button onClick={() => setPalette(true)} className="ml-auto flex h-10 min-w-0 flex-1 items-center gap-3 rounded-lg border border-border bg-muted/40 px-3 text-left text-sm text-muted-foreground sm:max-w-[430px]"><Search className="size-4" /><span className="truncate">Search books, members, authors, ISBN...</span><kbd className="ml-auto hidden rounded border border-border bg-background px-2 py-1 text-[10px] sm:block">⌘ K</kbd></button><button onClick={() => setDark(!dark)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Toggle theme">{dark ? <Sun className="size-[18px]" /> : <Moon className="size-[18px]" />}</button><button className="relative rounded-lg p-2 text-muted-foreground" aria-label="Notifications"><Bell className="size-[18px]" /></button><div className="hidden items-center gap-2 border-l border-border pl-3 md:flex"><span className="grid size-8 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">{currentUser.initials}</span><span className="text-xs font-medium">{currentUser.name}</span></div></header><main className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8">{children}</main></div></div>{palette && <div className="fixed inset-0 z-50 bg-foreground/20 p-4 pt-[12vh] backdrop-blur-sm" onMouseDown={() => setPalette(false)}><div className="mx-auto max-w-xl overflow-hidden rounded-2xl border border-border bg-popover shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center gap-3 border-b border-border px-4 py-4"><Command className="size-5 text-muted-foreground" /><input autoFocus className="flex-1 bg-transparent outline-none" placeholder="Search commands and pages..." onKeyDown={(event) => { if (event.key === 'Escape') setPalette(false) }} /></div><div className="p-2">{navItems.map((item) => <button key={item.href} onClick={() => go(item.href)} className="flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm hover:bg-muted"><ChevronRight className="size-4 text-muted-foreground" />{item.label}<span className="ml-auto text-xs text-muted-foreground">{item.href}</span></button>)}</div></div></div>}</div>
}

export function PageHeader({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="mb-8 flex flex-col gap-4 border-b border-border pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.18em] text-primary">BiblioNexus / {title}</p><h1 className="text-balance text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div>{action}</div> }
export function StateNotice({ kind, children }: { kind: 'loading' | 'empty' | 'error' | 'denied' | 'offline' | 'synced'; children: React.ReactNode }) { return <div className={cn('rounded-xl border p-4 text-sm', kind === 'error' || kind === 'denied' ? 'border-destructive/30 bg-destructive/5 text-destructive' : 'border-border bg-muted/30 text-muted-foreground')}>{children}</div> }

export function DataTable({ rows }: { rows: { title: string; author: string; isbn: string; format: string; status: string }[] }) { return <div className="overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full text-left text-sm"><thead className="border-b border-border bg-muted/30 text-xs text-muted-foreground"><tr>{['Title','Author','ISBN','Format','Status'].map((head) => <th className="px-4 py-3 font-medium" key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row) => <tr className="border-b border-border last:border-0 hover:bg-muted/20" key={row.isbn}><td className="px-4 py-4 font-medium">{row.title}</td><td className="px-4 py-4 text-muted-foreground">{row.author}</td><td className="px-4 py-4 font-mono text-xs text-muted-foreground">{row.isbn}</td><td className="px-4 py-4 text-muted-foreground">{row.format}</td><td className="px-4 py-4"><span className={cn('rounded-full px-2 py-1 text-xs', row.status === 'Available' ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300')}>{row.status}</span></td></tr>)}</tbody></table></div> }
